version: "3"
services:
  app:
    build:
      context: .
      args:
        - ENVIRONMENT = local
    ports:
      - 8080:8080
    entrypoint: ["uvicorn","app.main:appi","--host","0.0.0.0","--port","8080","--reload"]
    volumes:
      - .:/usr/src/workspace

  app-test:
    build:
      context: .
      args:
        - ENVIRONMENT = test
    # entrypoint: ["pytest","tests"]
    volumes:
      - .:/usr/src/workspace

# version: "3"
# services:
#   app:
#     build: ./
#     ports:
#       - 8080:8080
#     entrypoint: ["uvicorn","app.main:appi","--host","0.0.0.0","--port","8080","--reload"]
#     # entrypoint: pwd
#     volumes:
#       - ./:/usr/src/workspace

#   app-test:
#     build: .
#     volumes:
#       - ./:/usr/src/workspace

